/* tslint:disable */
/* eslint-disable */
/**
 * NoCode
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AddTemplateInput
 */
export interface AddTemplateInput {

    /**
     * @type {string}
     * @memberof AddTemplateInput
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof AddTemplateInput
     */
    code?: string | null;

    /**
     * @type {string}
     * @memberof AddTemplateInput
     */
    description?: string | null;

    /**
     * @type {number}
     * @memberof AddTemplateInput
     */
    dataSroucesId?: number;

    /**
     * @type {string}
     * @memberof AddTemplateInput
     */
    templateConfig?: string | null;
}
