/* tslint:disable */
/* eslint-disable */
/**
 * NoCode
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 系统菜单表
 *
 * @export
 * @interface PageTemplate
 */
export interface PageTemplate {

    /**
     * @type {number}
     * @memberof PageTemplate
     */
    id?: number;

    /**
     * @type {Date}
     * @memberof PageTemplate
     */
    createTime?: Date | null;

    /**
     * @type {Date}
     * @memberof PageTemplate
     */
    updateTime?: Date | null;

    /**
     * @type {number}
     * @memberof PageTemplate
     */
    createUserId?: number | null;

    /**
     * @type {string}
     * @memberof PageTemplate
     */
    createUserName?: string | null;

    /**
     * @type {number}
     * @memberof PageTemplate
     */
    updateUserId?: number | null;

    /**
     * @type {string}
     * @memberof PageTemplate
     */
    updateUserName?: string | null;

    /**
     * @type {boolean}
     * @memberof PageTemplate
     */
    isDelete?: boolean;

    /**
     * @type {number}
     * @memberof PageTemplate
     */
    orderNo?: number;

    /**
     * 名称
     *
     * @type {string}
     * @memberof PageTemplate
     */
    name: string;

    /**
     * 编码
     *
     * @type {string}
     * @memberof PageTemplate
     */
    code?: string | null;

    /**
     * 说明
     *
     * @type {string}
     * @memberof PageTemplate
     */
    description?: string | null;

    /**
     * 分类Id
     *
     * @type {number}
     * @memberof PageTemplate
     */
    dataSroucesId2?: number;

    /**
     * 说明
     *
     * @type {string}
     * @memberof PageTemplate
     */
    templateConfig?: string | null;

     /**
     * 启用
     *
     * @type {boolean}
     * @memberof PageTemplate
     */
     enabled: boolean ;

    /**
     * menuId
     *
     * @type {number}
     * @memberof PageTemplate
     */
    menuId?: number | null;

    /**
     * parentMenuId
     *
     * @type {number}
     * @memberof PageTemplate
     */
    parentMenuId?: number | null;
    
     /**
     * Icon
     *
     * @type {string}
     * @memberof PageTemplate
     */
    icon?: string | null;
}
