/* tslint:disable */
/* eslint-disable */
/**
 * NoCode
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PageTemplateInput
 */
export interface PageTemplateInput {

    /**
     * @type {number}
     * @memberof PageTemplateInput
     */
    page?: number;

    /**
     * @type {number}
     * @memberof PageTemplateInput
     */
    pageSize?: number;

    /**
     * @type {string}
     * @memberof PageTemplateInput
     */
    field?: string | null;

    /**
     * @type {string}
     * @memberof PageTemplateInput
     */
    order?: string | null;

    /**
     * @type {string}
     * @memberof PageTemplateInput
     */
    descStr?: string | null;

    /**
     * @type {string}
     * @memberof PageTemplateInput
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof PageTemplateInput
     */
    code?: string | null;
    
    
     /**
     * 启用
     *
     * @type {boolean}
     * @memberof PageTemplateInput
     */
     enabled: boolean ;

          
    /**
     * menuId
     *
     * @type {number}
     * @memberof PageTemplateInput
     */
    menuId?: number | null;

    /**
     * parentMenuId
     *
     * @type {number}
     * @memberof PageTemplateInput
     */
    parentMenuId?: number | null;
    
     /**
     * Icon
     *
     * @type {string}
     * @memberof PageTemplateInput
     */
    icon?: string | null;
}
