/* tslint:disable */
/* eslint-disable */
/**
 * NoCode
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PageTemplate } from './page-template';
 /**
 * 
 *
 * @export
 * @interface SqlSugarPagedListPageTemplate
 */
export interface SqlSugarPagedListPageTemplate {

    /**
     * @type {number}
     * @memberof SqlSugarPagedListPageTemplate
     */
    page?: number;

    /**
     * @type {number}
     * @memberof SqlSugarPagedListPageTemplate
     */
    pageSize?: number;

    /**
     * @type {number}
     * @memberof SqlSugarPagedListPageTemplate
     */
    total?: number;

    /**
     * @type {number}
     * @memberof SqlSugarPagedListPageTemplate
     */
    totalPages?: number;

    /**
     * @type {Array<PageTemplate>}
     * @memberof SqlSugarPagedListPageTemplate
     */
    items?: Array<PageTemplate> | null;

    /**
     * @type {boolean}
     * @memberof SqlSugarPagedListPageTemplate
     */
    hasPrevPage?: boolean;

    /**
     * @type {boolean}
     * @memberof SqlSugarPagedListPageTemplate
     */
    hasNextPage?: boolean;
}
