<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);SZLS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MessageQueue\Mqtt\**" />
    <Compile Remove="TcpClient\**" />
    <Compile Remove="TcpServer\**" />
    <EmbeddedResource Remove="MessageQueue\Mqtt\**" />
    <EmbeddedResource Remove="TcpClient\**" />
    <EmbeddedResource Remove="TcpServer\**" />
    <None Remove="MessageQueue\Mqtt\**" />
    <None Remove="TcpClient\**" />
    <None Remove="TcpServer\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EasyNetQ" Version="7.8.0" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DHY.Core\DHY.Core.csproj" />
  </ItemGroup>

</Project>
